/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Plan
         * @description Generate a chronological observation plan for a single night.
         */
        post: operations["generate_plan_plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/export/skylist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Plan Skylist
         * @description Generates and returns a SkySafari .skylist file for the plan.
         */
        post: operations["export_plan_skylist_plan_export_skylist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Plan Csv
         * @description Generates and returns a CSV file for the observation plan.
         */
        post: operations["export_plan_csv_plan_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Multi Night Forecast
         * @description Generate a multi-night imaging quality forecast.
         */
        get: operations["get_multi_night_forecast_plan_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/target-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Target Opportunity Series
         * @description Generate a high-resolution time-series of altitude and quality scores
         *     for a target.
         */
        get: operations["get_target_opportunity_series_plan_target_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Targets
         * @description lightweight endpoint to fetch only top recommended targets
         */
        post: operations["recommend_targets_plan_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/quality-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quality Series
         * @description generate a time-series of sky quality (Weather + Moon) for the night
         */
        get: operations["get_quality_series_plan_quality_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/sky-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sky View
         * @description Provides Moon and Target positions for animation throughout the night.
         */
        get: operations["get_sky_view_plan_sky_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Catalogs
         * @description Returns all available catalogs and their metadata.
         */
        get: operations["list_catalogs_catalogs__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Targets
         * @description Search for targets by name or identifier with optional filters.
         */
        get: operations["search_targets_targets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Target Detail
         * @description Get detailed information for a single target.
         */
        get: operations["get_target_detail_targets__target_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{target_id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Target Position
         * @description Generate a time-series of positions (Alt/Az) for a target.
         */
        get: operations["get_target_position_targets__target_id__position_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Returns a list of all telescope profiles.
         */
        get: operations["list_profiles_profiles__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locations
         * @description Returns all saved locations from the config file (Lakehouse).
         */
        get: operations["list_locations_locations__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Logs
         * @description Returns all observation logs.
         */
        get: operations["list_logs_logs__get"];
        put?: never;
        /**
         * Create Log
         * @description Creates a new observation log entry.
         */
        post: operations["create_log_logs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/target/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logs For Target
         * @description Returns all logs for a specific target.
         */
        get: operations["get_logs_for_target_logs_target__target_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Log
         * @description Deletes an observation log entry.
         */
        delete: operations["delete_log_logs__log_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description :return: the current application configuration
         */
        get: operations["get_settings_settings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Settings
         * @description updates the application configuration, triggering a lakehouse refresh
         *     if locations are modified
         *     :param update: the fields to update
         *     :return: the updated application configuration
         */
        patch: operations["update_settings_settings__patch"];
        trace?: never;
    };
    "/weather/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weather Forecast
         * @description get the weather forecast for a given location and timestamp
         *     :param latitude:
         *     :param longitude:
         *     :param timestamp:
         *     :param weather_service:
         *     :return:
         */
        get: operations["get_weather_forecast_weather__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weather Forecast Range
         * @description get weather forecasts for a time range at a location
         *     :param latitude:
         *     :param longitude:
         *     :param start:
         *     :param end:
         *     :param weather_service:
         *     :return:
         */
        get: operations["get_weather_forecast_range_weather_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description Returns the health status of the API.
         */
        get: operations["get_system_status_system__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/warm-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Warm Ephemeris Cache
         * @description Manually triggers the ephemeris cache warming process.
         */
        post: operations["warm_ephemeris_cache_system_warm_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfig */
        AppConfig: {
            /** Locations */
            locations: components["schemas"]["LocationConfig"][];
            planning: components["schemas"]["PlanningSettings"];
            integrations: components["schemas"]["IntegrationsSettings"];
            /**
             * @default {
             *       "level": "INFO",
             *       "max_size_mb": 10,
             *       "backup_count": 5
             *     }
             */
            logging: components["schemas"]["LoggingSettings"];
        };
        /**
         * CatalogItem
         * @description Metadata for an astronomical catalog.
         */
        CatalogItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Author */
            author?: string | null;
            /** Item Count */
            item_count: number;
        };
        /**
         * CatalogListResponse
         * @description Response wrapper for listing catalogs.
         */
        CatalogListResponse: {
            /** Catalogs */
            catalogs: components["schemas"]["CatalogItem"][];
        };
        /**
         * ForecastData
         * @description defines the structure of a single weather forecast data point for a specific
         *     location and time
         */
        ForecastData: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Temperature C */
            temperature_c: number | null;
            /** Cloud Cover Pct */
            cloud_cover_pct: number | null;
            /** Precipitation Mm Per Hour */
            precipitation_mm_per_hour: number | null;
            /** Precipitation Prob */
            precipitation_prob: number | null;
            /** Wind Speed Mps */
            wind_speed_mps: number | null;
            /** Wind Direction Deg */
            wind_direction_deg: number | null;
            /** Humidity Pct */
            humidity_pct: number | null;
            /** Seeing */
            seeing: number | null;
        };
        /** ForecastDay */
        ForecastDay: {
            /** Date */
            date: string;
            /** Astronomical Night Start */
            astronomical_night_start?: string | null;
            /** Astronomical Night End */
            astronomical_night_end?: string | null;
            /** Total Dark Hours */
            total_dark_hours: number;
            /** Effective Hours */
            effective_hours: number;
            /** Quality Score */
            quality_score: number;
            /**
             * Relative Quality
             * @default 0
             */
            relative_quality: number;
            /**
             * Absolute Quality
             * @default 0
             */
            absolute_quality: number;
            /** Note */
            note?: string | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Location Name */
            location_name: string;
            /** Days */
            days: components["schemas"]["ForecastDay"][];
        };
        /** FovFit */
        FovFit: {
            /** Fits Sensor */
            fits_sensor: boolean;
            /** Percent Of Frame */
            percent_of_frame: number;
            /** Orientation Suggested */
            orientation_suggested?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationsSettings */
        IntegrationsSettings: {
            weather: components["schemas"]["WeatherSettings"];
        };
        /** LocationConfig */
        LocationConfig: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Elevation M
             * @default 0
             */
            elevation_m: number;
            /** Bortle Scale */
            bortle_scale?: number | null;
            /**
             * Default
             * @default false
             */
            default: boolean;
        };
        /** LocationItem */
        LocationItem: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Elevation M
             * @default 0
             */
            elevation_m: number;
            /** Bortle Scale */
            bortle_scale?: number | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Timezone */
            timezone?: string | null;
            /** Horizon Mask */
            horizon_mask?: [
                number,
                number
            ][] | null;
        };
        /** LocationListResponse */
        LocationListResponse: {
            /** Locations */
            locations: components["schemas"]["LocationItem"][];
        };
        /** LoggingSettings */
        LoggingSettings: {
            /**
             * Level
             * @default INFO
             */
            level: string;
            /**
             * Max Size Mb
             * @default 10
             */
            max_size_mb: number;
            /**
             * Backup Count
             * @default 5
             */
            backup_count: number;
        };
        /** ObservationBlock */
        ObservationBlock: {
            /** Target Id */
            target_id: string;
            /** Common Name */
            common_name?: string | null;
            /** Target Type */
            target_type?: string | null;
            /** Constellation */
            constellation?: string | null;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Oss Score */
            oss_score: number;
            /** Aqs Score */
            aqs_score?: number | null;
        };
        /** ObservationLogCreate */
        ObservationLogCreate: {
            /** Target Id */
            target_id: string;
            /** Session Date */
            session_date?: string | null;
            /** Notes */
            notes?: string | null;
            /** Rating */
            rating?: number | null;
            /**
             * Status
             * @default Captured
             */
            status: string;
        };
        /** ObservationLogItem */
        ObservationLogItem: {
            /** Id */
            id: number;
            /** Target Id */
            target_id: string;
            /**
             * Session Date
             * Format: date
             */
            session_date: string;
            /** Notes */
            notes?: string | null;
            /** Rating */
            rating?: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ObservationLogListResponse */
        ObservationLogListResponse: {
            /** Logs */
            logs: components["schemas"]["ObservationLogItem"][];
        };
        /** OpportunityPoint */
        OpportunityPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Alt Deg */
            alt_deg: number;
            /** Score */
            score: number;
            /** Sqs */
            sqs: number;
        };
        /**
         * PlanRequest
         * @example {
         *       "bortle_scale": 5,
         *       "elevation_m": 0,
         *       "latitude": 35.75,
         *       "location_name": "Spring Hill TN",
         *       "longitude": -86.92,
         *       "min_alt": 30,
         *       "start_time": "2026-05-11T04:14:53.573403",
         *       "telescope_profile_name": "Seestar S30"
         *     }
         */
        PlanRequest: {
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Elevation M
             * @default 0
             */
            elevation_m: number;
            /** Telescope Profile Name */
            telescope_profile_name: string;
            /** Start Time */
            start_time?: string | null;
            /**
             * Min Alt
             * @default 30
             */
            min_alt: number;
            /** Location Name */
            location_name?: string | null;
            /** Bortle Scale */
            bortle_scale?: number | null;
            /**
             * Include Targets
             * @default []
             */
            include_targets: string[];
        };
        /** PlanResponse */
        PlanResponse: {
            /** Location Name */
            location_name: string;
            /** Astronomical Night Start */
            astronomical_night_start?: string | null;
            /** Astronomical Night End */
            astronomical_night_end?: string | null;
            /** Timeline */
            timeline: components["schemas"]["ObservationBlock"][];
            /**
             * Recommendations
             * @default []
             */
            recommendations: components["schemas"]["TargetRecommendation"][];
        };
        /** PlanningSettings */
        PlanningSettings: {
            /**
             * Default Telescope
             * @default Seestar S50
             */
            default_telescope: string | null;
            /**
             * Min Altitude
             * @default 25
             */
            min_altitude: number | null;
            /**
             * Max Altitude
             * @default 75
             */
            max_altitude: number | null;
            /**
             * Min Duration Minutes
             * @default 60
             */
            min_duration_minutes: number | null;
            /**
             * Block Size Minutes
             * @default 60
             */
            block_size_minutes: number | null;
            /**
             * Min Top Threshold
             * @default 50
             */
            min_top_threshold: number | null;
            /** Max Magnitude */
            max_magnitude?: number | null;
            /** Min Angular Size Arcmin */
            min_angular_size_arcmin?: number | null;
            /** Max Surface Brightness */
            max_surface_brightness?: number | null;
        };
        /** PositionPoint */
        PositionPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Alt Deg */
            alt_deg: number;
            /** Az Deg */
            az_deg: number;
        };
        /**
         * ProfileListResponse
         * @description Response wrapper for listing telescope profiles.
         */
        ProfileListResponse: {
            /** Profiles */
            profiles: components["schemas"]["TelescopeProfileItem"][];
        };
        /** QualityPoint */
        QualityPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Score */
            score: number;
            /** Moon Mult */
            moon_mult: number;
            /** Weather Mult */
            weather_mult: number;
            /**
             * Seeing Mult
             * @default 1
             */
            seeing_mult: number | null;
        };
        /** QualitySeriesResponse */
        QualitySeriesResponse: {
            /** Location Name */
            location_name: string;
            /** Points */
            points: components["schemas"]["QualityPoint"][];
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Locations */
            locations?: components["schemas"]["LocationConfig"][] | null;
            planning?: components["schemas"]["PlanningSettings"] | null;
            integrations?: components["schemas"]["IntegrationsSettings"] | null;
            logging?: components["schemas"]["LoggingSettings"] | null;
        };
        /** SkyStatusPoint */
        SkyStatusPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Moon Alt */
            moon_alt: number;
            /** Moon Az */
            moon_az: number;
            /** Moon Phase */
            moon_phase: number;
            /** Sky Quality Rel */
            sky_quality_rel: number;
            /** Sky Quality Abs */
            sky_quality_abs: number;
            /** Target Positions */
            target_positions: {
                [key: string]: components["schemas"]["PositionPoint"];
            };
        };
        /** SkyViewResponse */
        SkyViewResponse: {
            /** Location Name */
            location_name: string;
            /** Timeline */
            timeline: components["schemas"]["SkyStatusPoint"][];
        };
        /** TargetDetail */
        TargetDetail: {
            /** Identifier */
            identifier: string;
            /** Ra Deg */
            ra_deg: number;
            /** Dec Deg */
            dec_deg: number;
            /** Target Type */
            target_type: string;
            /** Magnitude */
            magnitude?: number | null;
            /** Angular Size */
            angular_size?: number[] | null;
            /** Distance */
            distance?: number | null;
            /** Constellation */
            constellation?: string | null;
            /** Common Name */
            common_name?: string | null;
            /** Catalog Id */
            catalog_id: string;
            /** Catalog Name */
            catalog_name?: string | null;
            /**
             * Identifiers
             * @default []
             */
            identifiers: string[] | null;
            fov_fit?: components["schemas"]["FovFit"] | null;
            /** Last Observed */
            last_observed?: string | null;
            /** Observation Count */
            observation_count?: number | null;
        };
        /** TargetOpportunitySeries */
        TargetOpportunitySeries: {
            /** Target Id */
            target_id: string;
            /** Location Name */
            location_name: string;
            /** Points */
            points: components["schemas"]["OpportunityPoint"][];
        };
        /** TargetPositionSeries */
        TargetPositionSeries: {
            /** Identifier */
            identifier: string;
            /** Positions */
            positions: components["schemas"]["PositionPoint"][];
        };
        /** TargetRecommendation */
        TargetRecommendation: {
            /** Target Id */
            target_id: string;
            /** Common Name */
            common_name?: string | null;
            /** Target Type */
            target_type: string;
            /** Constellation */
            constellation: string;
            /** Magnitude */
            magnitude?: number | null;
            /** Oss Score */
            oss_score: number;
            /** Aqs Score */
            aqs_score?: number | null;
            /** Sqs Score */
            sqs_score: number;
            /** Final Score */
            final_score: number;
            /** Visible Start */
            visible_start?: string | null;
            /** Visible End */
            visible_end?: string | null;
        };
        /** TargetSearchItem */
        TargetSearchItem: {
            /** Identifier */
            identifier: string;
            /** Common Name */
            common_name?: string | null;
            /** Target Type */
            target_type: string;
            /** Constellation */
            constellation: string;
            /** Magnitude */
            magnitude?: number | null;
            /** Angular Size */
            angular_size?: number[] | null;
            /** Season */
            season?: string | null;
        };
        /** TargetSearchResponse */
        TargetSearchResponse: {
            /** Results */
            results: components["schemas"]["TargetSearchItem"][];
            /** Total Found */
            total_found: number;
        };
        /**
         * TelescopeProfileItem
         * @description Metadata for a telescope hardware configuration.
         */
        TelescopeProfileItem: {
            /** Name */
            name: string;
            /** Aperture Mm */
            aperture_mm: number;
            /** Focal Length Mm */
            focal_length_mm: number;
            /** Sensor X */
            sensor_x: number;
            /** Sensor Y */
            sensor_y: number;
            /** Pixel Pitch Um */
            pixel_pitch_um: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherSettings */
        WeatherSettings: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Provider
             * @default dummy
             */
            provider: string;
            /** Api Key */
            api_key?: string | null;
            /**
             * Units
             * @default C
             */
            units: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_plan_plan_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_plan_skylist_plan_export_skylist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_plan_csv_plan_export_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_multi_night_forecast_plan_forecast_get: {
        parameters: {
            query?: {
                latitude?: number | null;
                longitude?: number | null;
                location_name?: string | null;
                days?: number;
                start_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_target_opportunity_series_plan_target_series_get: {
        parameters: {
            query: {
                target_id: string;
                location_name: string;
                telescope_profile_name: string;
                start_time?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetOpportunitySeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_targets_plan_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetRecommendation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_series_plan_quality_series_get: {
        parameters: {
            query: {
                location_name: string;
                start_time?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sky_view_plan_sky_view_get: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                location_name?: string;
                start_time?: string | null;
                target_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkyViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catalogs_catalogs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogListResponse"];
                };
            };
        };
    };
    search_targets_targets_search_get: {
        parameters: {
            query?: {
                q?: string;
                target_type?: string | null;
                constellation?: string | null;
                max_magnitude?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_target_detail_targets__target_id__get: {
        parameters: {
            query?: {
                profile_name?: string | null;
            };
            header?: never;
            path: {
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_target_position_targets__target_id__position_get: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                start_time: string;
                hours?: number;
            };
            header?: never;
            path: {
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetPositionSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_profiles__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
        };
    };
    list_locations_locations__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationListResponse"];
                };
            };
        };
    };
    list_logs_logs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationLogListResponse"];
                };
            };
        };
    };
    create_log_logs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationLogItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_for_target_logs_target__target_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_log_logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    update_settings_settings__patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weather_forecast_weather__get: {
        parameters: {
            query: {
                /** @description Latitude */
                latitude: number;
                /** @description Longitude */
                longitude: number;
                /** @description ISO-8601 timestamp for the forecast */
                timestamp: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weather_forecast_range_weather_range_get: {
        parameters: {
            query: {
                /** @description Latitude */
                latitude: number;
                /** @description Longitude */
                longitude: number;
                /** @description ISO-8601 start timestamp for the forecast */
                start: string;
                /** @description ISO-8601 end timestamp for the forecast */
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastData"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_status_system__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    warm_ephemeris_cache_system_warm_cache_post: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
