server {
    listen 8080;
    server_name localhost;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    root /usr/share/nginx/html;

    location /stairs-docs/ {
        index index.html;
        try_files $uri $uri/ /stairs-docs/index.html;
    }

    # Redirect root to the docs
    location = / {
        return 301 /stairs-docs/;
    }

    # Error handling
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
