name: Build and Release Images

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - api
          - cli
          - web
        include:
          - service: api
            context: .
            dockerfile: ./services/api/Dockerfile
            image_name: stairs-api
          - service: cli
            context: ./services/cli
            dockerfile: ./services/cli/Dockerfile
            image_name: stairs-cli
          - service: web
            context: ./services/web
            dockerfile: ./services/web/Dockerfile
            image_name: stairs-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lowercase repository name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to the container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ env.REPO_LOWER }}/${{ matrix.image_name }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push docker image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
